name: NerdPlot
main: org.challenger2.NerdPlot.NerdPlotPlugin
version: ${project.version}
description: ${project.description}
website: ${project.url}
depend: [WorldGuard, WorldEdit, WGCustomFlags]
authors: [Challenger2]
commands:
  nerdplot:
    description: NerdPlot Commands
    usage: /<command> help
permissions:
  nerdplot.create:
    description: Create a new plot
